import { GeistSans } from "geist/font/sans";
import { type PropsWithChildren } from "react";
import { Toaster } from "~/components/ui/sonner";
import TRPCReactProvider from "~/providers/trpc-react-provider";
import "~/styles/globals.css";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="nl" className={`${GeistSans.variable}`}>
            <body>
                <TRPCReactProvider>
                    <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-[#191714] to-[#2234AE] text-white">
                        {children}
                    </main>
                    <Toaster />
                </TRPCReactProvider>
            </body>
        </html>
    );
}
